namespace PowerToolbox.Extensions.DataType.Enums
{
    /// <summary>
    /// 操作通知类型
    /// </summary>
    public enum OperationKind
    {
        AddDriverAllSuccessfully = 0,
        AddDriverFailed = 1,
        AddDriverPartialSuccessfully = 2,
        AddInstallDriverAllSuccessfully = 3,
        AddInstallDriverFailed = 4,
        AddInstallDriverPartialSuccessfully = 5,
        CleanUpdateHistory = 6,
        CheckUpdate = 7,
        ContextMenuUpdate = 8,
        CustomFileFilterTypeEmpty = 9,
        DeleteDriverAllSuccessfully = 10,
        DeleteDriverFailed = 11,
        DeleteDriverPartialSuccessfully = 12,
        DeleteDriverSuccessfully = 13,
        DeleteFileFailed = 14,
        Desktop = 15,
        File = 16,
        FileLost = 17,
        ForceDeleteDriverAllSuccessfully = 18,
        ForceDeleteDriverFailed = 19,
        ForceDeleteDriverPartialSuccessfully = 20,
        ForceDeleteDriverSuccessfully = 21,
        IconExtract = 22,
        InsiderPreviewSettings = 23,
        LanguageChange = 24,
        ListEmpty = 25,
        LogClean = 26,
        LoopbackSetResult = 27,
        MenuDarkThemeIconPathEmpty = 28,
        MenuDefaultIconPathEmpty = 29,
        MenuLightThemeIconPathEmpty = 30,
        MenuProgramPathEmpty = 31,
        MenuMatchRuleEmpty = 32,
        MenuTitleEmpty = 33,
        NoOperation = 34,
        RestoreContentEmpty = 35,
        RestoreSpecificExtensionGroupsTypeEmpty = 36,
        SameDriveAndSelectFolder = 37,
        SelectDriverEmpty = 38,
        SelectFolderEmpty = 39,
        SelectLogFolderEmpty = 40,
        ShellMenuNeedToRefreshData = 41,
        StartScreen = 42,
        Taskbar = 43,
        TerminateProcess = 44,
        ThemeChangeSameTime = 45,
        ThemeSwitchSaveResult = 46,
        ThemeSwitchRestoreResult = 47,
    }
}
