namespace PowerToolbox.Extensions.DataType.Enums
{
    /// <summary>
    /// 操作通知类型
    /// </summary>
    public enum OperationKind
    {
        AddDriverAllSuccessfully = 0,
        AddDriverFailed = 1,
        AddDriverPartialSuccessfully = 2,
        AddInstallDriverAllSuccessfully = 3,
        AddInstallDriverFailed = 4,
        AddInstallDriverPartialSuccessfully = 5,
        CleanUpdateHistory = 6,
        CheckUpdate = 7,
        ContextMenuUpdate = 8,
        CustomFileFilterTypeEmpty = 9,
        DeleteDriverAllSuccessfully = 10,
        DeleteDriverFailed = 11,
        DeleteDriverPartialSuccessfully = 12,
        DeleteDriverSuccessfully = 13,
        DeleteFileFailed = 14,
        Desktop = 15,
        DriveEmpty = 16,
        File = 17,
        FileLost = 18,
        ForceDeleteDriverAllSuccessfully = 19,
        ForceDeleteDriverFailed = 20,
        ForceDeleteDriverPartialSuccessfully = 21,
        ForceDeleteDriverSuccessfully = 22,
        IconExtract = 23,
        InsiderPreviewSettings = 24,
        LanguageChange = 25,
        ListEmpty = 26,
        LogClean = 27,
        LoopbackSetResult = 28,
        MenuDarkThemeIconPathEmpty = 29,
        MenuDefaultIconPathEmpty = 30,
        MenuLightThemeIconPathEmpty = 31,
        MenuProgramPathEmpty = 32,
        MenuMatchRuleEmpty = 33,
        MenuTitleEmpty = 34,
        NoOperation = 35,
        RestoreContentEmpty = 36,
        RestoreSpecificExtensionGroupsTypeEmpty = 37,
        SameDriveAndSelectFolder = 38,
        ScheduledTaskDelete = 39,
        ScheduledTaskDisable = 40,
        ScheduledTaskEnable = 41,
        ScheduledTaskExport = 42,
        ScheduledTaskRun = 43,
        ScheduledTaskStop = 44,
        SelectDriverEmpty = 45,
        SelectFolderEmpty = 46,
        SelectLogFolderEmpty = 47,
        ShellMenuNeedToRefreshData = 48,
        StartScreen = 49,
        Taskbar = 50,
        TerminateProcess = 51,
        ThemeChangeSameTime = 52,
        ThemeSwitchSaveResult = 53,
        ThemeSwitchRestoreResult = 54,
        WinFRNotInstalled = 55
    }
}
